version: '3.8'

services:
  backend:
    build:
      context: ./ShopAPIBackend
      dockerfile: Dockerfile
    container_name: shop_backend
    restart: always
    ports:
      - "5131:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=postgres;Username=sudenazkocabicak;
      - GroqSettings__ApiKey=${GROQ_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./ShopAPIFrontend
      dockerfile: Dockerfile
    container_name: shop_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
